### PR TITLE
Graph 256 - Transaction Handler

### PR DESCRIPTION
**Pull request by kruspy**
[GRAPH-256](https://figmentio.atlassian.net/browse/GRAPH-256)

### CODE REVIEW

**Review by lavabyrd — APPROVED** [review]
LGTM

**Review by lavabyrd — APPROVED** [review]
LGTM,

**Comment by lavabyrd** [comment]
actually just thinking @kruspy , should this merge into `cosmos` instead of main so you have the updated `tx` protobuf too?

**Comment by kruspy** [comment]
> actually just thinking @kruspy , should this merge into `cosmos` instead of main so you have the updated `tx` protobuf too?

Transaction handler is not dependant on the transaction decoding, that is why I am merging it to main, so the handler can be used via tendermint branches without the need of the decoding works. It is also true that the handler lacks a bit of purpose without the transaction decoding. Therefore, I would still merge it to main if we are periodically merging main into cosmos, if not,  I will merge it to cosmos directly.

**Comment by pienkowb** [comment]
@lavabyrd I think this should be merged into `main` too, the `cosmos` branch is still experimental.

**Pull request merged**
