### PR TITLE
Add a directory structure

### PR DESCRIPTION
**Pull request by pienkowb**
This separates the codec protobufs from transform protobufs.

### CODE REVIEW

**Comment by lavabyrd** [comment]
should we not version the output directory too? if we're hard coding the v1 into the `make generate` then we can probable just set the codec to `/codec/v1` or similar

**Comment by pienkowb** [comment]
> should we not version the output directory too? if we're hard coding the v1 into the `make generate` then we can probable just set the codec to `/codec/v1` or similar

It's a really good idea but it would break compatibility in other repos (different import path).

I think we should do that anyway and probably move the generated files under `pb` (like [here](https://github.com/streamingfast/sf-near/tree/develop/pb)). What do you think?

**Comment by lavabyrd** [comment]
> > should we not version the output directory too? if we're hard coding the v1 into the `make generate` then we can probable just set the codec to `/codec/v1` or similar
> 
> It's a really good idea but it would break compatibility in other repos (different import path).
> 
> I think we should do that anyway and probably move the generated files under `pb` (like [here](https://github.com/streamingfast/sf-near/tree/develop/pb)). What do you think?

I wonder if we could do both for now so we have a /codec/codec.proto and then a v1 style structure also so we can have backwards capability and then look at deprecating it slowly over time. Its DRY style code unfortunately but it means we have everything in place and can make the switch bit by bit which maintaining one codec.proto which means one .pb.go source of truth but in two places.

we may be able to just tack on a `cp codec.pb.go ../codec/v1/codec.pb.go` or similar to the `make generate` to do this

**Comment by pienkowb** [comment]
> > > should we not version the output directory too? if we're hard coding the v1 into the `make generate` then we can probable just set the codec to `/codec/v1` or similar
> > 
> > 
> > It's a really good idea but it would break compatibility in other repos (different import path).
> > I think we should do that anyway and probably move the generated files under `pb` (like [here](https://github.com/streamingfast/sf-near/tree/develop/pb)). What do you think?
> 
> I wonder if we could do both for now so we have a /codec/codec.proto and then a v1 style structure also so we can have backwards capability and then look at deprecating it slowly over time. Its DRY style code unfortunately but it means we have everything in place and can make the switch bit by bit which maintaining one codec.proto which means one .pb.go source of truth but in two places.
> 
> we may be able to just tack on a `cp codec.pb.go ../codec/v1/codec.pb.go` or similar to the `make generate` to do this

This makes a lot of sense but we are going to make changes that will break compatibility anyway (e.g. rename `tendermint` to cosmos`, change `fig` to `firehose`), so there's no way we could avoid keeping the import paths intact.

**Comment by lavabyrd** [comment]
> > > > should we not version the output directory too? if we're hard coding the v1 into the `make generate` then we can probable just set the codec to `/codec/v1` or similar
> > > 
> > > 
> > > It's a really good idea but it would break compatibility in other repos (different import path).
> > > I think we should do that anyway and probably move the generated files under `pb` (like [here](https://github.com/streamingfast/sf-near/tree/develop/pb)). What do you think?
> > 
> > 
> > I wonder if we could do both for now so we have a /codec/codec.proto and then a v1 style structure also so we can have backwards capability and then look at deprecating it slowly over time. Its DRY style code unfortunately but it means we have everything in place and can make the switch bit by bit which maintaining one codec.proto which means one .pb.go source of truth but in two places.
> > we may be able to just tack on a `cp codec.pb.go ../codec/v1/codec.pb.go` or similar to the `make generate` to do this
> 
> This makes a lot of sense but we are going to make changes that will break compatibility anyway (e.g. rename `tendermint` to `cosmos`, change `fig` to `firehose`), so there's no way we could avoid keeping the import paths intact.

very true. We can just make sure we change the paths when we update the versions on the depending apps anyway. 🚢

**Review by lavabyrd — APPROVED** [review]

**Review by Seb-figment — APPROVED** [review]
LGTM

**Pull request merged**
